plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17.21'
    id 'maven-publish'
}

def globalModVersion = project.findProperty('mod_version') ?: '2.2.0'
def globalGroup = project.findProperty('maven_group') ?: 'net.sakura.weapons'
def globalBaseName = project.findProperty('archives_base_name') ?: 'Takasha'

version = "${globalModVersion}+1.21.11"
group = globalGroup

base {
    archivesName = globalBaseName
}

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

sourceSets {
    main {
        resources {
            srcDirs += [
                "${rootDir}/shared-resources"
            ]
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named('build') {
    doLast {
        def builtJar = tasks.findByName('remapJar') ? tasks.remapJar.archiveFile.get().asFile : tasks.jar.archiveFile.get().asFile
        copy {
            from builtJar
            into file("${rootDir}/../Hasil mod")
        }
    }
}
