# Memory settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Users/Administrator/AppData/Roaming/.minecraft/runtime/java-runtime-epsilon/windows/java-runtime-epsilon

# Mod Properties & Versioning
mod_version=2.2.0
maven_group=net.sakura.weapons
archives_base_name=Takasha
